# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CollectIp.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1006, 752)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.info = QtWidgets.QLabel(self.groupBox_2)
        self.info.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.info.setObjectName("info")
        self.gridLayout.addWidget(self.info, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.start = QtWidgets.QPushButton(self.groupBox_2)
        self.start.setObjectName("start")
        self.gridLayout.addWidget(self.start, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(402, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkFull = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkFull.setObjectName("checkFull")
        self.gridLayout_2.addWidget(self.checkFull, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.dataView = QtWidgets.QTableWidget(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("Monospac821 BT")
        font.setPointSize(10)
        self.dataView.setFont(font)
        self.dataView.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.dataView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.dataView.setObjectName("dataView")
        self.dataView.setColumnCount(3)
        self.dataView.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dataView.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataView.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataView.setHorizontalHeaderItem(2, item)
        self.gridLayout_2.addWidget(self.dataView, 1, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.actionCheck_All = QtWidgets.QAction(Form)
        self.actionCheck_All.setObjectName("actionCheck_All")
        self.actionCopy = QtWidgets.QAction(Form)
        self.actionCopy.setObjectName("actionCopy")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CollectProxyIP"))
        self.groupBox_2.setTitle(_translate("Form", "Abstract"))
        self.info.setText(_translate("Form", "Collect proxy IP."))
        self.label.setText(_translate("Form", "The data has been stored in ../common/proxyIP.py"))
        self.start.setToolTip(_translate("Form", "start crawling(Shift+S)"))
        self.start.setText(_translate("Form", "start"))
        self.start.setShortcut(_translate("Form", "Shift+S"))
        self.groupBox_3.setTitle(_translate("Form", "Data display"))
        self.checkFull.setText(_translate("Form", "Full"))
        item = self.dataView.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Time"))
        item = self.dataView.horizontalHeaderItem(1)
        item.setText(_translate("Form", "IP"))
        item = self.dataView.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Data"))
        self.actionCheck_All.setText(_translate("Form", "Check All"))
        self.actionCheck_All.setShortcut(_translate("Form", "Ctrl+A"))
        self.actionCopy.setText(_translate("Form", "Copy"))
        self.actionCopy.setToolTip(_translate("Form", "Copy"))
        self.actionCopy.setShortcut(_translate("Form", "Ctrl+C"))
