# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Filter(object):
    def setupUi(self, Filter):
        Filter.setObjectName("Filter")
        Filter.resize(396, 375)
        Filter.setMinimumSize(QtCore.QSize(387, 357))
        Filter.setMaximumSize(QtCore.QSize(409, 394))
        self.gridLayout_2 = QtWidgets.QGridLayout(Filter)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(Filter)
        self.groupBox.setMinimumSize(QtCore.QSize(361, 251))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 46, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.IP = QtWidgets.QLabel(self.groupBox)
        self.IP.setObjectName("IP")
        self.gridLayout.addWidget(self.IP, 1, 0, 1, 1)
        self.FilterIP = QtWidgets.QLineEdit(self.groupBox)
        self.FilterIP.setInputMask("")
        self.FilterIP.setText("")
        self.FilterIP.setPlaceholderText("Example:127.0.0.1")
        self.FilterIP.setClearButtonEnabled(True)
        self.FilterIP.setObjectName("FilterIP")
        self.gridLayout.addWidget(self.FilterIP, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 46, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 1, 1, 1)
        self.Data = QtWidgets.QLabel(self.groupBox)
        self.Data.setObjectName("Data")
        self.gridLayout.addWidget(self.Data, 3, 0, 1, 1)
        self.FilterData = QtWidgets.QLineEdit(self.groupBox)
        self.FilterData.setText("")
        self.FilterData.setPlaceholderText("Example:《三体》")
        self.FilterData.setClearButtonEnabled(True)
        self.FilterData.setObjectName("FilterData")
        self.gridLayout.addWidget(self.FilterData, 3, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 102, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Filter)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Filter)
        QtCore.QMetaObject.connectSlotsByName(Filter)

        self.buttonBox.accepted.connect(Filter.accept)
        self.buttonBox.rejected.connect(Filter.reject)
        QtCore.QMetaObject.connectSlotsByName(Filter)

    def retranslateUi(self, Filter):
        _translate = QtCore.QCoreApplication.translate
        Filter.setWindowTitle(_translate("Filter", "Filter"))
        self.groupBox.setTitle(_translate("Filter", "Keyword Filter"))
        self.IP.setText(_translate("Filter", "IP:"))
        self.FilterIP.setToolTip(_translate("Filter", "<html><head/><body><p>Displays the data that exists in the input IP</p></body></html>"))
        self.FilterIP.setStatusTip(_translate("Filter", "IP Filter"))
        self.Data.setText(_translate("Filter", "Data:"))
        self.FilterData.setToolTip(_translate("Filter", "<html><head/><body><p>Displays the data that exists in the input Data</p></body></html>"))
        self.FilterData.setStatusTip(_translate("Filter", "Content Filtering"))
