# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ZoomeyeConfigToken.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ZoomeyeConfig(object):
    def setupUi(self, ZoomeyeConfig):
        ZoomeyeConfig.setObjectName("ZoomeyeConfig")
        ZoomeyeConfig.resize(654, 588)
        self.gridLayout_2 = QtWidgets.QGridLayout(ZoomeyeConfig)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(ZoomeyeConfig)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 401))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(120, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.Grammar = QtWidgets.QPushButton(self.groupBox)
        self.Grammar.setMaximumSize(QtCore.QSize(61, 28))
        self.Grammar.setObjectName("Grammar")
        self.gridLayout.addWidget(self.Grammar, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 5, 3, 1)
        self.Token = QtWidgets.QLabel(self.groupBox)
        self.Token.setMinimumSize(QtCore.QSize(0, 61))
        self.Token.setMaximumSize(QtCore.QSize(48, 16777215))
        self.Token.setObjectName("Token")
        self.gridLayout.addWidget(self.Token, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(64, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 4, 0, 1, 6)
        self.ZoomToken = QtWidgets.QLineEdit(self.groupBox)
        self.ZoomToken.setMinimumSize(QtCore.QSize(0, 61))
        self.ZoomToken.setText("")
        self.ZoomToken.setPlaceholderText("Token")
        self.ZoomToken.setClearButtonEnabled(True)
        self.ZoomToken.setObjectName("ZoomToken")
        self.gridLayout.addWidget(self.ZoomToken, 2, 1, 1, 4)
        self.Keyword = QtWidgets.QLineEdit(self.splitter_2)
        self.Keyword.setMaximumSize(QtCore.QSize(16777215, 51))
        self.Keyword.setText("")
        self.Keyword.setPlaceholderText("Keyword")
        self.Keyword.setClearButtonEnabled(True)
        self.Keyword.setObjectName("Keyword")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.message = QtWidgets.QLabel(self.splitter)
        self.message.setObjectName("message")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.splitter)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)

        self.retranslateUi(ZoomeyeConfig)
        self.buttonBox.accepted.connect(ZoomeyeConfig.accept)
        self.buttonBox.rejected.connect(ZoomeyeConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(ZoomeyeConfig)

    def retranslateUi(self, ZoomeyeConfig):
        _translate = QtCore.QCoreApplication.translate
        ZoomeyeConfig.setWindowTitle(_translate("ZoomeyeConfig", "ZoomeConfig"))
        self.groupBox.setTitle(_translate("ZoomeyeConfig", "ZoomeyeConfig"))
        self.label.setText(_translate("ZoomeyeConfig", "The password used to log in to ZoomEye."))
        self.Grammar.setText(_translate("ZoomeyeConfig", "···"))
        self.Token.setText(_translate("ZoomeyeConfig", "token:"))
        self.ZoomToken.setToolTip(_translate("ZoomeyeConfig", "<html><head/><body><p>Token</p></body></html>"))
        self.ZoomToken.setStatusTip(_translate("ZoomeyeConfig", "Password"))
        self.Keyword.setToolTip(_translate("ZoomeyeConfig", "<html><head/><body><p>Search Keyword</p></body></html>"))
        self.Keyword.setStatusTip(_translate("ZoomeyeConfig", "Verification"))
        self.message.setText(_translate("ZoomeyeConfig", "Login successfully"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ZoomeyeConfig = QtWidgets.QDialog()
    ui = Ui_ZoomeyeConfig()
    ui.setupUi(ZoomeyeConfig)
    ZoomeyeConfig.show()
    sys.exit(app.exec_())
